cookbook_app/config/routes.rb
Rails.application.routes.draw do

  root 'recipes#index'
  resources :recipes
  resources :ingredients
  resources :categories
  resources :quantities

end

cookbook_app/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :recipes

  validates :title, presence: true

end

cookbook_app/app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :quantities
  has_many :recipes, through: :quantities

  validates :title, presence: true

end

cookbook_app/app/models/quantity.rb
class Quantity < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe

  validates :amount, presence: true

end

cookbook_app/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :category
  has_many :quantities
  has_many :ingredients, through: :quantities

  validates :category_id, numericality: {only_integer: true}

end

cookbook_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

cookbook_app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    Category.create(category_params)
    redirect_to(categories_path)
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])
    category.update(category_params)
    redirect_to(categories_path)
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    redirect_to(categories_path)
  end

  private
  def category_params
    params.require(:category).permit(:title)
  end

end

cookbook_app/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    Ingredient.create(ingredient_params)
    redirect_to(ingredients_path)
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    ingredient = Ingredient.find(params[:id])
    ingredient.update(ingredient_params)
    redirect_to(ingredients_path)
  end

  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.destroy
    redirect_to(ingredients_path)
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:title, :type, :quantities)
  end

end

cookbook_app/app/controllers/quantities_controller.rb
class QuantitiesController < ApplicationController

  def index
    @quantities = Quantity.all
  end

  def new
    @quantities = Quantity.new
    @recipes = Recipe.all
    @ingredients = Ingredient.all
  end

  def create
    Quantity.create(quantity_params)
    redirect_to(quantities_path)
  end

  def show
    @quantity = Quantity.find(params[:id])
  end

  def edit
    @quantity = Quantity.find(params[:id])
    @recipes = Recipe.all
    @ingredients = Ingredient.all
  end

  def update
    quantity = Quantity.find(params[:id])
    quantity.update(quantity_params)
    redirect_to(quantities_path)
  end

  def destroy
    quantity = Quantity.find(params[:id])
    quantity.destroy
    redirect_to(quantities_path)
  end

  private
  def quantity_params
    params.require(:quantity).permit(:amount, :recipe_id, :ingredient_id)
  end

end

cookbook_app/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @categories = Category.all
  end

  def create
    Category.find(params[:recipe][:category_id]).recipes.create(recipe_params)
    redirect_to(category_path(params[:recipe][:category_id]))
  end

  def show
    @recipe = Recipe.find(params[:id])
    @quantities = Quantity.where(:recipe_id => params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
    @categories = Category.all
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.update(recipe_params)
    redirect_to(recipes_path)
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to(recipes_path)
  end

  private
  def recipe_params
    params.require(:recipe).permit(:title, :description, :instructions, :img, :category_id, :quantities)
  end

end

cookbook_app/app/helpers/application_helper.rb
module ApplicationHelper
end

cookbook_app/app/views/categories/edit.html.erb
<h1>Edit Category Details</h1>

<%= form_for @category do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true %>
  <br>

  <%= f.submit 'Edit Category' %>

<% end %>

cookbook_app/app/views/categories/index.html.erb
<h1>
  Categories
</h1>
<hr>

<p>
  <% @categories.each do |category| %>
  <h3> <%= link_to("#{category.title}", category_path(category)) %> </h3>
  <br>
  <%= link_to("Edit Category", edit_category_path(category)) %>
  <h4>
    <%= link_to("Delete Category", category_path(category), method: :delete, data: {confirm: "Do you wish to delete this category?"}) %>
  </h4>
  <hr>
</p>
<% end %>
<h2><%= link_to('Enter New Category', new_category_path) %></h2>

cookbook_app/app/views/categories/new.html.erb
<h1>Enter New Category Details</h1>

<%= form_for @category do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true %>
  <br>

  <%= f.submit 'Add Category' %>

<% end %>

cookbook_app/app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<% @category.recipes.each do |recipe| %>

<%= link_to("#{recipe.title}", recipe_path(recipe)) %>
<br>
<%= image_tag(recipe.img, alt: 'No image') %>
<br>
<br>
<% end %>

cookbook_app/app/views/ingredients/edit.html.erb
<h1>Edit Ingredient Details</h1>

<%= form_for @ingredient do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true %>
  <br>

  <%= f.label :kind %>
  <%= f.text_field :kind %>
  <br>

  <%= f.submit 'Edit Ingredient' %>

<% end %>

cookbook_app/app/views/ingredients/index.html.erb
<h1>
  Ingredients
</h1>
<hr>

<p>
  <% @ingredients.each do |ingredient| %>
  <h3> <%= link_to("#{ingredient.title}", ingredient_path(ingredient)) %> </h3>
  <br>
  <%= ingredient.kind %>
  <br>
  <%= link_to("Edit Ingredient", edit_ingredient_path(ingredient)) %>
  <h4>
    <%= link_to("Delete Ingredient", ingredient_path(ingredient), method: :delete, data: {confirm: "Do you wish to delete this ingredient?"}) %>
  </h4>
  <hr>
</p>
<% end %>

cookbook_app/app/views/ingredients/new.html.erb
<h1>Enter New Ingredient Details</h1>

<%= form_for @ingredient do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, :autofocus => true %>
  <br>

  <%= f.label :kind %>
  <%= f.text_field :kind %>
  <br>

  <%= f.submit 'Add Ingredient' %>

<% end %>

cookbook_app/app/views/ingredients/show.html.erb
<h1><%= @ingredient.title %></h1>
<br>
  <%= @ingredient.kind %>
  <br>
  <br>

cookbook_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookbookApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Paula Deen's Butter Emporium</h1>
  <header>
    <nav>
      <ul>
        <li>
          <%= link_to('See all recipes', recipes_path) %>
        </li>
        <li>
          <%= link_to('Enter new recipe', new_recipe_path) %>
        </li>
        <li>
          <%= link_to('See recipes by category', categories_path) %>
        </li>
        <li>
          <%= link_to('See recipes by ingredient', ingredients_path) %>
        </li>
      </ul>
    </nav>
  </header>

  <%= yield %>

</body>
</html>

cookbook_app/app/views/recipes/edit.html.erb
<h1>Edit Recipe Details</h1>

<%= form_for @recipe do |f| %>
<%= f.label :title %>
<%= f.text_field :title, :autofocus => true %>
<br>

<%= f.label :description %>
<%= f.text_area :description %>
<br>

<%= f.label :instructions %>
<%= f.text_area :instructions %>
<br>

<%= f.label :img, 'Image URL' %>
<%= f.text_field :img %>
<br>

<p>Please choose a category:
  <br>
  <% @categories.each do |c| %>
  <%= f.radio_button(:category_id, "#{c.id}") %>
  <%= f.label(":category_id_#{c.id}", "#{c.title}") %>
  <br>
  <% end %>
</p>

<%= f.submit 'Edit Recipe' %>

<% end %>

cookbook_app/app/views/recipes/index.html.erb
<h1>
  Recipes
</h1>


<p>
  <% @recipes.each do |recipe| %>
  <h3> <%= link_to("#{recipe.title}", recipe_path(recipe)) %> </h3>
  <br>
  <%= recipe.description %>
  <br>
  <%= image_tag(recipe.img, alt: 'No image') %>
  <br>
  <%= link_to("Edit Recipe", edit_recipe_path(recipe)) %>
  <h4>
    <%= link_to("Delete Recipe", recipe_path(recipe), method: :delete, data: {confirm: "Do you wish to delete this recipe?"}) %>
  </h4>
  <hr>
</p>

<!-- Add Ingredients/Category data -->

<% end %>

cookbook_app/app/views/recipes/new.html.erb
<h1>Add a Recipe</h1>

<%= form_for @recipe do |f| %>
<%= f.label :title %>
<%= f.text_field :title, :autofocus => true %>
<br>

<%= f.label :description %>
<%= f.text_area :description %>
<br>

<%= f.label :instructions %>
<%= f.text_area :instructions %>
<br>

<%= f.label :img, 'Image URL' %>
<%= f.text_field :img %>
<br>

<p>Please choose a category:
  <br>
  <% @categories.each do |c| %>
  <%= f.radio_button(:category_id, "#{c.id}") %>
  <%= f.label(":category_id_#{c.id}", "#{c.title}") %>
  <br>
  <% end %>
</p>

<%= f.submit 'Add Recipe' %>

<% end %>

cookbook_app/app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>
Category: <%= link_to("#{@recipe.category.title}", category_path(@recipe.category_id)) %>
<br> 
<%= image_tag(@recipe.img, alt:'No image', class: 'img') %>
<br>
<br>
<p>
  Description: <%= @recipe.description %>
  <br>
 Instructions: <%= @recipe.instructions %>
<br>

Ingredients:
<% @quantities.each do |quantity| %> <br>
<!--   <%= link_to(recipe_id: @recipe.id, ingredient_id: quantity.ingredient_id, return_page: 'recipe') %>
  <br> -->
  <%= link_to("#{Ingredient.find(quantity.ingredient_id).title}", ingredient_path(Ingredient.find(quantity.ingredient_id)) ) %>

  <%= form_for quantity do |f| %>
    <%= f.label :amount %>
    <%= f.text_field :amount %>
    <%= f.submit "Save" %>
  <% end %>
  <% end %>

</p>